# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Home.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!
import socket

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ui_home(object):
    def setupUi(self, ui_home):
        ui_home.setObjectName("ui_home")
        ui_home.resize(1180, 814)
        ui_home.setAutoFillBackground(False)
        self.grafico = QtWidgets.QTabWidget(ui_home)
        self.grafico.setEnabled(True)
        self.grafico.setGeometry(QtCore.QRect(0, 0, 1191, 861))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.grafico.setFont(font)
        self.grafico.setMouseTracking(False)
        self.grafico.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.grafico.setObjectName("grafico")
        self.pagina_inicial = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(14)
        self.pagina_inicial.setFont(font)
        self.pagina_inicial.setStyleSheet("#pagina_inicial{\n"
"background-color: qlineargradient(spread:pad, x1:0.095, y1:0.903, x2:0.994, y2:0.0113636, stop:0 rgba(123, 91, 255, 255), stop:0.716418 rgba(22, 47, 168, 255));\n"
"}")
        self.pagina_inicial.setObjectName("pagina_inicial")
        self.label = QtWidgets.QLabel(self.pagina_inicial)
        self.label.setGeometry(QtCore.QRect(80, 80, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_cadastrar_loja = QtWidgets.QPushButton(self.pagina_inicial)
        self.btn_cadastrar_loja.setEnabled(True)
        self.btn_cadastrar_loja.setGeometry(QtCore.QRect(80, 140, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(16)
        self.btn_cadastrar_loja.setFont(font)
        self.btn_cadastrar_loja.setMouseTracking(False)
        self.btn_cadastrar_loja.setStyleSheet("#btn_cadastrar_loja{\n"
"background-color:#ffffff;\n"
"border-radius: 5px;\n"
"}")
        self.btn_cadastrar_loja.setObjectName("btn_cadastrar_loja")
        self.btn_cadastrar_funcionario = QtWidgets.QPushButton(self.pagina_inicial)
        self.btn_cadastrar_funcionario.setGeometry(QtCore.QRect(80, 190, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(16)
        self.btn_cadastrar_funcionario.setFont(font)
        self.btn_cadastrar_funcionario.setStyleSheet("#btn_cadastrar_funcionario{\n"
"background-color:#ffffff;\n"
"border-radius: 5px;\n"
"}")
        self.btn_cadastrar_funcionario.setObjectName("btn_cadastrar_funcionario")
        self.btn_cadastrar_produto = QtWidgets.QPushButton(self.pagina_inicial)
        self.btn_cadastrar_produto.setGeometry(QtCore.QRect(80, 240, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(16)
        self.btn_cadastrar_produto.setFont(font)
        self.btn_cadastrar_produto.setStyleSheet("#btn_cadastrar_produto{\n"
"background-color:#ffffff;\n"
"border-radius: 5px;\n"
"}")
        self.btn_cadastrar_produto.setObjectName("btn_cadastrar_produto")
        self.label_2 = QtWidgets.QLabel(self.pagina_inicial)
        self.label_2.setGeometry(QtCore.QRect(790, 50, 231, 61))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.btn_atualizar_dia = QtWidgets.QPushButton(self.pagina_inicial)
        self.btn_atualizar_dia.setGeometry(QtCore.QRect(810, 120, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(16)
        self.btn_atualizar_dia.setFont(font)
        self.btn_atualizar_dia.setObjectName("btn_atualizar_dia")
        self.btn_atualizar_mes = QtWidgets.QPushButton(self.pagina_inicial)
        self.btn_atualizar_mes.setGeometry(QtCore.QRect(970, 120, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(16)
        self.btn_atualizar_mes.setFont(font)
        self.btn_atualizar_mes.setObjectName("btn_atualizar_mes")
        self.btn_atualizar = QtWidgets.QPushButton(self.pagina_inicial)
        self.btn_atualizar.setGeometry(QtCore.QRect(650, 120, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(16)
        self.btn_atualizar.setFont(font)
        self.btn_atualizar.setObjectName("btn_atualizar")
        self.gridLayoutWidget = QtWidgets.QWidget(self.pagina_inicial)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(650, 170, 471, 381))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lb_loja_conect = QtWidgets.QLabel(self.pagina_inicial)
        self.lb_loja_conect.setGeometry(QtCore.QRect(1090, 750, 67, 17))
        self.lb_loja_conect.setText("")
        self.lb_loja_conect.setObjectName("lb_loja_conect")
        self.grafico.addTab(self.pagina_inicial, "")
        self.buscar_produto = QtWidgets.QWidget()
        self.buscar_produto.setStyleSheet("#buscar_produto{\n"
"background-color: qlineargradient(spread:pad, x1:0.095, y1:0.903, x2:0.994, y2:0.0113636, stop:0 rgba(123, 91, 255, 255), stop:0.716418 rgba(22, 47, 168, 255));\n"
"}")
        self.buscar_produto.setObjectName("buscar_produto")
        self.label_12 = QtWidgets.QLabel(self.buscar_produto)
        self.label_12.setGeometry(QtCore.QRect(470, 100, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.txt_nome_produto = QtWidgets.QLineEdit(self.buscar_produto)
        self.txt_nome_produto.setGeometry(QtCore.QRect(560, 190, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(16)
        self.txt_nome_produto.setFont(font)
        self.txt_nome_produto.setStyleSheet("#txt_nome_produto{\n"
"border-radius: 5px;\n"
"}")
        self.txt_nome_produto.setObjectName("txt_nome_produto")
        self.txt_id_produto = QtWidgets.QLineEdit(self.buscar_produto)
        self.txt_id_produto.setGeometry(QtCore.QRect(560, 280, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(16)
        self.txt_id_produto.setFont(font)
        self.txt_id_produto.setStyleSheet("#txt_id_produto{\n"
"border-radius: 5px;\n"
"}")
        self.txt_id_produto.setObjectName("txt_id_produto")
        self.frame_4 = QtWidgets.QFrame(self.buscar_produto)
        self.frame_4.setGeometry(QtCore.QRect(200, 90, 801, 281))
        self.frame_4.setStyleSheet("#frame_4{\n"
"background-color:rgb(194, 194, 194);\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.btn_buscar_produto = QtWidgets.QPushButton(self.frame_4)
        self.btn_buscar_produto.setGeometry(QtCore.QRect(690, 240, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_buscar_produto.setFont(font)
        self.btn_buscar_produto.setStyleSheet("#btn_buscar_produto{\n"
"background-color:rgb(138, 226, 52);\n"
"border-radius: 5px;\n"
"}")
        self.btn_buscar_produto.setObjectName("btn_buscar_produto")
        self.label_13 = QtWidgets.QLabel(self.frame_4)
        self.label_13.setGeometry(QtCore.QRect(160, 100, 191, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame_4)
        self.label_14.setGeometry(QtCore.QRect(160, 190, 161, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.cb_nome_produto = QtWidgets.QCheckBox(self.frame_4)
        self.cb_nome_produto.setGeometry(QtCore.QRect(120, 110, 16, 17))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(16)
        self.cb_nome_produto.setFont(font)
        self.cb_nome_produto.setText("")
        self.cb_nome_produto.setObjectName("cb_nome_produto")
        self.cb_id_produto = QtWidgets.QCheckBox(self.frame_4)
        self.cb_id_produto.setGeometry(QtCore.QRect(120, 200, 16, 17))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(16)
        self.cb_id_produto.setFont(font)
        self.cb_id_produto.setText("")
        self.cb_id_produto.setObjectName("cb_id_produto")
        self.layoutWidget = QtWidgets.QWidget(self.buscar_produto)
        self.layoutWidget.setGeometry(QtCore.QRect(170, 460, 801, 29))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(16)
        self.layoutWidget.setFont(font)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cv_mostrar_produtos = QtWidgets.QColumnView(self.buscar_produto)
        self.cv_mostrar_produtos.setGeometry(QtCore.QRect(200, 490, 801, 192))
        self.cv_mostrar_produtos.setStyleSheet("#cv_mostrar_produtos{\n"
"border-radius: 5px;\n"
"}")
        self.cv_mostrar_produtos.setObjectName("cv_mostrar_produtos")
        self.label_16 = QtWidgets.QLabel(self.buscar_produto)
        self.label_16.setGeometry(QtCore.QRect(402, 451, 196, 27))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(16)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_15 = QtWidgets.QLabel(self.buscar_produto)
        self.label_15.setGeometry(QtCore.QRect(201, 451, 195, 27))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(16)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_18 = QtWidgets.QLabel(self.buscar_produto)
        self.label_18.setGeometry(QtCore.QRect(805, 451, 195, 27))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(16)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_17 = QtWidgets.QLabel(self.buscar_produto)
        self.label_17.setGeometry(QtCore.QRect(604, 451, 195, 27))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(16)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.layoutWidget.raise_()
        self.frame_4.raise_()
        self.label_12.raise_()
        self.txt_nome_produto.raise_()
        self.txt_id_produto.raise_()
        self.cv_mostrar_produtos.raise_()
        self.label_16.raise_()
        self.label_15.raise_()
        self.label_18.raise_()
        self.label_17.raise_()
        self.grafico.addTab(self.buscar_produto, "")
        self.buscar_loja = QtWidgets.QWidget()
        self.buscar_loja.setStyleSheet("#buscar_loja{\n"
"background-color: qlineargradient(spread:pad, x1:0.095, y1:0.903, x2:0.994, y2:0.0113636, stop:0 rgba(123, 91, 255, 255), stop:0.716418 rgba(22, 47, 168, 255));\n"
"}")
        self.buscar_loja.setObjectName("buscar_loja")
        self.label_25 = QtWidgets.QLabel(self.buscar_loja)
        self.label_25.setGeometry(QtCore.QRect(540, 110, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.buscar_loja)
        self.label_26.setGeometry(QtCore.QRect(350, 200, 161, 27))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.buscar_loja)
        self.label_27.setGeometry(QtCore.QRect(350, 260, 141, 27))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.cb_nome_filial = QtWidgets.QCheckBox(self.buscar_loja)
        self.cb_nome_filial.setGeometry(QtCore.QRect(271, 210, 16, 16))
        self.cb_nome_filial.setText("")
        self.cb_nome_filial.setObjectName("cb_nome_filial")
        self.cb_id_loja = QtWidgets.QCheckBox(self.buscar_loja)
        self.cb_id_loja.setGeometry(QtCore.QRect(271, 271, 16, 16))
        self.cb_id_loja.setText("")
        self.cb_id_loja.setObjectName("cb_id_loja")
        self.txt_nome_filial = QtWidgets.QLineEdit(self.buscar_loja)
        self.txt_nome_filial.setGeometry(QtCore.QRect(540, 200, 311, 33))
        self.txt_nome_filial.setStyleSheet("#txt_nome_filial{\n"
"border-radius: 5px;\n"
"}")
        self.txt_nome_filial.setObjectName("txt_nome_filial")
        self.frame = QtWidgets.QFrame(self.buscar_loja)
        self.frame.setGeometry(QtCore.QRect(229, 90, 741, 301))
        self.frame.setStyleSheet("#frame{\n"
"background-color:rgb(194, 194, 194);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btn_buscar_loja = QtWidgets.QPushButton(self.frame)
        self.btn_buscar_loja.setGeometry(QtCore.QRect(620, 250, 91, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        self.btn_buscar_loja.setFont(font)
        self.btn_buscar_loja.setStyleSheet("#btn_buscar_loja{\n"
"background-color:rgb(138, 226, 52);\n"
"border-radius: 5px;\n"
"}")
        self.btn_buscar_loja.setObjectName("btn_buscar_loja")
        self.sb_id_loja = QtWidgets.QSpinBox(self.frame)
        self.sb_id_loja.setGeometry(QtCore.QRect(310, 170, 311, 41))
        self.sb_id_loja.setStyleSheet("#sb_id_loja{\n"
"border-radius: 5px;\n"
"}")
        self.sb_id_loja.setMaximum(1000)
        self.sb_id_loja.setObjectName("sb_id_loja")
        self.cv_mostrar_loja = QtWidgets.QColumnView(self.buscar_loja)
        self.cv_mostrar_loja.setGeometry(QtCore.QRect(230, 480, 741, 192))
        self.cv_mostrar_loja.setStyleSheet("#cv_mostrar_loja{\n"
"border-radius: 5px;\n"
"}")
        self.cv_mostrar_loja.setObjectName("cv_mostrar_loja")
        self.label_28 = QtWidgets.QLabel(self.buscar_loja)
        self.label_28.setGeometry(QtCore.QRect(231, 431, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.buscar_loja)
        self.label_29.setGeometry(QtCore.QRect(484, 431, 481, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_28.raise_()
        self.label_29.raise_()
        self.frame.raise_()
        self.label_25.raise_()
        self.label_26.raise_()
        self.label_27.raise_()
        self.cb_nome_filial.raise_()
        self.cb_id_loja.raise_()
        self.txt_nome_filial.raise_()
        self.cv_mostrar_loja.raise_()
        self.grafico.addTab(self.buscar_loja, "")
        self.ver_estoque = QtWidgets.QWidget()
        self.ver_estoque.setStyleSheet("#ver_estoque{\n"
"background-color: qlineargradient(spread:pad, x1:0.095, y1:0.903, x2:0.994, y2:0.0113636, stop:0 rgba(123, 91, 255, 255), stop:0.716418 rgba(22, 47, 168, 255));\n"
"}")
        self.ver_estoque.setObjectName("ver_estoque")
        self.label_19 = QtWidgets.QLabel(self.ver_estoque)
        self.label_19.setGeometry(QtCore.QRect(280, 110, 111, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.cb_nome_prod_estoque = QtWidgets.QCheckBox(self.ver_estoque)
        self.cb_nome_prod_estoque.setGeometry(QtCore.QRect(251, 79, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(16)
        self.cb_nome_prod_estoque.setFont(font)
        self.cb_nome_prod_estoque.setText("")
        self.cb_nome_prod_estoque.setObjectName("cb_nome_prod_estoque")
        self.label_20 = QtWidgets.QLabel(self.ver_estoque)
        self.label_20.setGeometry(QtCore.QRect(280, 70, 191, 24))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.cb_id_loja_estoque = QtWidgets.QCheckBox(self.ver_estoque)
        self.cb_id_loja_estoque.setGeometry(QtCore.QRect(250, 120, 70, 17))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(16)
        self.cb_id_loja_estoque.setFont(font)
        self.cb_id_loja_estoque.setText("")
        self.cb_id_loja_estoque.setObjectName("cb_id_loja_estoque")
        self.frame_2 = QtWidgets.QFrame(self.ver_estoque)
        self.frame_2.setGeometry(QtCore.QRect(170, 40, 931, 171))
        self.frame_2.setStyleSheet("#frame_2{\n"
"background-color:rgb(194, 194, 194);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.txt_nome_produto_estoque = QtWidgets.QLineEdit(self.frame_2)
        self.txt_nome_produto_estoque.setGeometry(QtCore.QRect(310, 30, 431, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(16)
        self.txt_nome_produto_estoque.setFont(font)
        self.txt_nome_produto_estoque.setStyleSheet("#txt_nome_produto_estoque{\n"
"border-radius: 5px;\n"
"}")
        self.txt_nome_produto_estoque.setObjectName("txt_nome_produto_estoque")
        self.sb_id_loja_estoque = QtWidgets.QSpinBox(self.frame_2)
        self.sb_id_loja_estoque.setGeometry(QtCore.QRect(310, 70, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(16)
        self.sb_id_loja_estoque.setFont(font)
        self.sb_id_loja_estoque.setStyleSheet("#sb_id_loja_estoque{\n"
"border-radius: 5px;\n"
"}")
        self.sb_id_loja_estoque.setMaximum(1000)
        self.sb_id_loja_estoque.setObjectName("sb_id_loja_estoque")
        self.btn_ver_estoque = QtWidgets.QPushButton(self.frame_2)
        self.btn_ver_estoque.setGeometry(QtCore.QRect(740, 110, 161, 32))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        self.btn_ver_estoque.setFont(font)
        self.btn_ver_estoque.setStyleSheet("#btn_ver_estoque{\n"
"background-color:rgb(138, 226, 52);\n"
"border-radius: 5px;\n"
"}")
        self.btn_ver_estoque.setObjectName("btn_ver_estoque")
        self.cv_estoque = QtWidgets.QColumnView(self.ver_estoque)
        self.cv_estoque.setGeometry(QtCore.QRect(170, 300, 931, 411))
        self.cv_estoque.setStyleSheet("#cv_estoque{\n"
"border-radius: 5px;\n"
"}")
        self.cv_estoque.setObjectName("cv_estoque")
        self.label_21 = QtWidgets.QLabel(self.ver_estoque)
        self.label_21.setGeometry(QtCore.QRect(171, 251, 231, 25))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(16)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.ver_estoque)
        self.label_22.setGeometry(QtCore.QRect(320, 250, 231, 25))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(16)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.ver_estoque)
        self.label_23.setGeometry(QtCore.QRect(710, 250, 231, 25))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(16)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.ver_estoque)
        self.label_24.setGeometry(QtCore.QRect(910, 250, 231, 25))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(16)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.label_21.raise_()
        self.label_22.raise_()
        self.label_23.raise_()
        self.label_24.raise_()
        self.frame_2.raise_()
        self.label_19.raise_()
        self.cb_nome_prod_estoque.raise_()
        self.label_20.raise_()
        self.cb_id_loja_estoque.raise_()
        self.cv_estoque.raise_()
        self.grafico.addTab(self.ver_estoque, "")
        self.identificador_loja = QtWidgets.QWidget()
        self.identificador_loja.setStyleSheet("#identificador_loja{\n"
"background-color: qlineargradient(spread:pad, x1:0.095, y1:0.903, x2:0.994, y2:0.0113636, stop:0 rgba(123, 91, 255, 255), stop:0.716418 rgba(22, 47, 168, 255));\n"
"}")
        self.identificador_loja.setObjectName("identificador_loja")
        self.label_3 = QtWidgets.QLabel(self.identificador_loja)
        self.label_3.setGeometry(QtCore.QRect(740, 90, 181, 41))
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.sb_loja_conectada = QtWidgets.QSpinBox(self.identificador_loja)
        self.sb_loja_conectada.setGeometry(QtCore.QRect(740, 140, 181, 41))
        self.sb_loja_conectada.setStyleSheet("#sb_loja_conectada{\n"
"border-radius: 5px;\n"
"}")
        self.sb_loja_conectada.setMaximum(100000)
        self.sb_loja_conectada.setObjectName("sb_loja_conectada")
        self.label_4 = QtWidgets.QLabel(self.identificador_loja)
        self.label_4.setGeometry(QtCore.QRect(280, 90, 261, 41))
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.sb_func_conectado = QtWidgets.QSpinBox(self.identificador_loja)
        self.sb_func_conectado.setGeometry(QtCore.QRect(280, 140, 261, 41))
        self.sb_func_conectado.setStyleSheet("#sb_func_conectado{\n"
"border-radius: 5px;\n"
"}")
        self.sb_func_conectado.setMaximum(1000)
        self.sb_func_conectado.setDisplayIntegerBase(10)
        self.sb_func_conectado.setObjectName("sb_func_conectado")
        self.txt_senha_conectada = QtWidgets.QTextEdit(self.identificador_loja)
        self.txt_senha_conectada.setGeometry(QtCore.QRect(280, 220, 261, 41))
        self.txt_senha_conectada.setStyleSheet("#txt_senha_conectada{\n"
"border-radius: 5px;\n"
"}")
        self.txt_senha_conectada.setObjectName("txt_senha_conectada")
        self.label_5 = QtWidgets.QLabel(self.identificador_loja)
        self.label_5.setGeometry(QtCore.QRect(280, 180, 261, 41))
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.frame_3 = QtWidgets.QFrame(self.identificador_loja)
        self.frame_3.setGeometry(QtCore.QRect(210, 80, 771, 231))
        self.frame_3.setStyleSheet("#frame_3{\n"
"background-color:rgb(194, 194, 194);\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_5 = QtWidgets.QFrame(self.identificador_loja)
        self.frame_5.setGeometry(QtCore.QRect(210, 380, 771, 231))
        self.frame_5.setStyleSheet("#frame_5{\n"
"background-color:rgb(194, 194, 194);\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_7 = QtWidgets.QLabel(self.frame_5)
        self.label_7.setGeometry(QtCore.QRect(60, 20, 301, 41))
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.txt_ip_server = QtWidgets.QTextEdit(self.frame_5)
        self.txt_ip_server.setGeometry(QtCore.QRect(60, 80, 261, 41))
        self.txt_ip_server.setStyleSheet("#txt_senha_conectada{\n"
"border-radius: 5px;\n"
"}")
        self.txt_ip_server.setObjectName("txt_ip_server")
        self.btn_conect_server = QtWidgets.QPushButton(self.frame_5)
        self.btn_conect_server.setGeometry(QtCore.QRect(510, 80, 99, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_conect_server.setFont(font)
        self.btn_conect_server.setObjectName("btn_conect_server")
        self.label_6 = QtWidgets.QLabel(self.identificador_loja)
        self.label_6.setGeometry(QtCore.QRect(210, 340, 261, 41))
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.frame_3.raise_()
        self.label_3.raise_()
        self.sb_loja_conectada.raise_()
        self.label_4.raise_()
        self.sb_func_conectado.raise_()
        self.txt_senha_conectada.raise_()
        self.label_5.raise_()
        self.frame_5.raise_()
        self.label_6.raise_()
        self.grafico.addTab(self.identificador_loja, "")

        self.retranslateUi(ui_home)
        self.grafico.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(ui_home)

    def retranslateUi(self, ui_home):
        _translate = QtCore.QCoreApplication.translate
        ui_home.setWindowTitle(_translate("ui_home", "Dialog"))
        self.label.setText(_translate("ui_home", "MENU DE OPÇÕES"))
        self.btn_cadastrar_loja.setText(_translate("ui_home", "Cadastra Loja"))
        self.btn_cadastrar_funcionario.setText(_translate("ui_home", "Cadastrar Funcionário"))
        self.btn_cadastrar_produto.setText(_translate("ui_home", "Cadastrar Produto"))
        self.label_2.setText(_translate("ui_home", "Gráfico de Compras"))
        self.btn_atualizar_dia.setText(_translate("ui_home", "Do dia"))
        self.btn_atualizar_mes.setText(_translate("ui_home", "Do mês"))
        self.btn_atualizar.setText(_translate("ui_home", "Atualizar"))
        self.grafico.setTabText(self.grafico.indexOf(self.pagina_inicial), _translate("ui_home", "Página Inicial"))
        self.label_12.setText(_translate("ui_home", "Buscar Produto"))
        self.btn_buscar_produto.setText(_translate("ui_home", "Buscar"))
        self.label_13.setText(_translate("ui_home", "Nome do Produto"))
        self.label_14.setText(_translate("ui_home", "Identificador"))
        self.label_16.setText(_translate("ui_home", "Nome"))
        self.label_15.setText(_translate("ui_home", "Id"))
        self.label_18.setText(_translate("ui_home", "Preço Uni."))
        self.label_17.setText(_translate("ui_home", "Quantidade"))
        self.grafico.setTabText(self.grafico.indexOf(self.buscar_produto), _translate("ui_home", "Buscar Produto"))
        self.label_25.setText(_translate("ui_home", "Buscar Loja"))
        self.label_26.setText(_translate("ui_home", "Nome da Filial"))
        self.label_27.setText(_translate("ui_home", "Identificador"))
        self.btn_buscar_loja.setText(_translate("ui_home", "Buscar"))
        self.label_28.setText(_translate("ui_home", "Id"))
        self.label_29.setText(_translate("ui_home", "Nome"))
        self.grafico.setTabText(self.grafico.indexOf(self.buscar_loja), _translate("ui_home", "Buscar Loja"))
        self.label_19.setText(_translate("ui_home", "Id da Loja"))
        self.label_20.setText(_translate("ui_home", "Nome do Produto"))
        self.btn_ver_estoque.setText(_translate("ui_home", "Ver Estoque"))
        self.label_21.setText(_translate("ui_home", "Id_Produto"))
        self.label_22.setText(_translate("ui_home", "Nome"))
        self.label_23.setText(_translate("ui_home", "Quantidade"))
        self.label_24.setText(_translate("ui_home", "Id_loja"))
        self.grafico.setTabText(self.grafico.indexOf(self.ver_estoque), _translate("ui_home", "Ver Estoque"))
        self.label_3.setText(_translate("ui_home", "Loja Conectada"))
        self.label_4.setText(_translate("ui_home", "Funcionario Conetado"))
        self.label_5.setText(_translate("ui_home", "Senha"))
        self.label_7.setText(_translate("ui_home", "Informe o IP do Servidor"))
        self.btn_conect_server.setText(_translate("ui_home", "Conectar"))
        self.label_6.setText(_translate("ui_home", "Conectar ao Servidor"))
        self.grafico.setTabText(self.grafico.indexOf(self.identificador_loja), _translate("ui_home", "Page"))

        self.funcionalidades()

    def funcionalidades(self):
        #click de botões
        self.btn_conect_server.clicked.connect(self.conectarServer)

    def conectarServer(self):
        ip = self.txt_ip_server.toPlainText()
        print(ip)
        port = 7000
        addr = ((ip,port))
        client_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        client_socket.connect(addr)
        print("Entrou!")
        a = "Criar Cliente,"
        client_socket.send((a.encode()))
        mensagem_recebida = client_socket.recv(1024).decode()
        QtWidgets.QMessageBox.about(None, "Conectar", mensagem_recebida)
        client_socket.close()









if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui_home = QtWidgets.QDialog()
    ui = Ui_ui_home()
    ui.setupUi(ui_home)
    ui_home.show()
    sys.exit(app.exec_())
