# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Home.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import socket

class Ui_ui_home(object):
    def setupUi(self, ui_home):
        ui_home.setObjectName("ui_home")
        ui_home.resize(1180, 814)
        ui_home.setAutoFillBackground(False)
        self.grafico = QtWidgets.QTabWidget(ui_home)
        self.grafico.setEnabled(True)
        self.grafico.setGeometry(QtCore.QRect(0, 0, 1191, 861))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(12)
        self.grafico.setFont(font)
        self.grafico.setMouseTracking(False)
        self.grafico.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.grafico.setObjectName("grafico")
        self.pagina_inicial = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(14)
        self.pagina_inicial.setFont(font)
        self.pagina_inicial.setStyleSheet("")
        self.pagina_inicial.setObjectName("pagina_inicial")
        self.label = QtWidgets.QLabel(self.pagina_inicial)
        self.label.setGeometry(QtCore.QRect(80, 80, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_cadastrar_loja = QtWidgets.QPushButton(self.pagina_inicial)
        self.btn_cadastrar_loja.setEnabled(True)
        self.btn_cadastrar_loja.setGeometry(QtCore.QRect(80, 140, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(16)
        self.btn_cadastrar_loja.setFont(font)
        self.btn_cadastrar_loja.setMouseTracking(False)
        self.btn_cadastrar_loja.setStyleSheet("")
        self.btn_cadastrar_loja.setObjectName("btn_cadastrar_loja")
        self.btn_cadastrar_funcionario = QtWidgets.QPushButton(self.pagina_inicial)
        self.btn_cadastrar_funcionario.setGeometry(QtCore.QRect(80, 190, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(16)
        self.btn_cadastrar_funcionario.setFont(font)
        self.btn_cadastrar_funcionario.setStyleSheet("")
        self.btn_cadastrar_funcionario.setObjectName("btn_cadastrar_funcionario")
        self.btn_cadastrar_produto = QtWidgets.QPushButton(self.pagina_inicial)
        self.btn_cadastrar_produto.setGeometry(QtCore.QRect(80, 240, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(16)
        self.btn_cadastrar_produto.setFont(font)
        self.btn_cadastrar_produto.setStyleSheet("")
        self.btn_cadastrar_produto.setObjectName("btn_cadastrar_produto")
        self.label_2 = QtWidgets.QLabel(self.pagina_inicial)
        self.label_2.setGeometry(QtCore.QRect(790, 50, 231, 61))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.btn_atualizar_dia = QtWidgets.QPushButton(self.pagina_inicial)
        self.btn_atualizar_dia.setGeometry(QtCore.QRect(810, 120, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(16)
        self.btn_atualizar_dia.setFont(font)
        self.btn_atualizar_dia.setObjectName("btn_atualizar_dia")
        self.btn_atualizar_mes = QtWidgets.QPushButton(self.pagina_inicial)
        self.btn_atualizar_mes.setGeometry(QtCore.QRect(970, 120, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(16)
        self.btn_atualizar_mes.setFont(font)
        self.btn_atualizar_mes.setObjectName("btn_atualizar_mes")
        self.btn_atualizar = QtWidgets.QPushButton(self.pagina_inicial)
        self.btn_atualizar.setGeometry(QtCore.QRect(650, 120, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(16)
        self.btn_atualizar.setFont(font)
        self.btn_atualizar.setObjectName("btn_atualizar")
        self.gridLayoutWidget = QtWidgets.QWidget(self.pagina_inicial)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(660, 310, 471, 381))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lb_loja_conect = QtWidgets.QLabel(self.pagina_inicial)
        self.lb_loja_conect.setGeometry(QtCore.QRect(1090, 750, 67, 17))
        self.lb_loja_conect.setText("")
        self.lb_loja_conect.setObjectName("lb_loja_conect")
        self.data_inicial = QtWidgets.QDateEdit(self.pagina_inicial)
        self.data_inicial.setGeometry(QtCore.QRect(660, 226, 131, 31))
        self.data_inicial.setObjectName("data_inicial")
        self.date_final = QtWidgets.QDateEdit(self.pagina_inicial)
        self.date_final.setGeometry(QtCore.QRect(830, 226, 131, 31))
        self.date_final.setObjectName("date_final")
        self.label_3 = QtWidgets.QLabel(self.pagina_inicial)
        self.label_3.setGeometry(QtCore.QRect(660, 170, 191, 51))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.grafico.addTab(self.pagina_inicial, "")
        self.buscar_loja = QtWidgets.QWidget()
        self.buscar_loja.setStyleSheet("")
        self.buscar_loja.setObjectName("buscar_loja")
        self.label_25 = QtWidgets.QLabel(self.buscar_loja)
        self.label_25.setGeometry(QtCore.QRect(540, 110, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.buscar_loja)
        self.label_26.setGeometry(QtCore.QRect(350, 200, 161, 27))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.buscar_loja)
        self.label_27.setGeometry(QtCore.QRect(350, 260, 141, 27))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.cb_nome_filial = QtWidgets.QCheckBox(self.buscar_loja)
        self.cb_nome_filial.setGeometry(QtCore.QRect(271, 210, 16, 16))
        self.cb_nome_filial.setText("")
        self.cb_nome_filial.setObjectName("cb_nome_filial")
        self.cb_id_loja = QtWidgets.QCheckBox(self.buscar_loja)
        self.cb_id_loja.setGeometry(QtCore.QRect(271, 271, 16, 16))
        self.cb_id_loja.setText("")
        self.cb_id_loja.setObjectName("cb_id_loja")
        self.txt_nome_filial = QtWidgets.QLineEdit(self.buscar_loja)
        self.txt_nome_filial.setGeometry(QtCore.QRect(540, 200, 311, 33))
        self.txt_nome_filial.setStyleSheet("#txt_nome_filial{\n"
"border-radius: 5px;\n"
"}")
        self.txt_nome_filial.setObjectName("txt_nome_filial")
        self.frame = QtWidgets.QFrame(self.buscar_loja)
        self.frame.setGeometry(QtCore.QRect(229, 90, 741, 301))
        self.frame.setStyleSheet("#frame{\n"
"background-color:rgb(194, 194, 194);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btn_buscar_loja = QtWidgets.QPushButton(self.frame)
        self.btn_buscar_loja.setGeometry(QtCore.QRect(620, 250, 91, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        self.btn_buscar_loja.setFont(font)
        self.btn_buscar_loja.setStyleSheet("#btn_buscar_loja{\n"
"background-color:rgb(138, 226, 52);\n"
"border-radius: 5px;\n"
"}")
        self.btn_buscar_loja.setObjectName("btn_buscar_loja")
        self.sb_id_loja = QtWidgets.QSpinBox(self.frame)
        self.sb_id_loja.setGeometry(QtCore.QRect(310, 170, 311, 41))
        self.sb_id_loja.setStyleSheet("#sb_id_loja{\n"
"border-radius: 5px;\n"
"}")
        self.sb_id_loja.setMaximum(1000)
        self.sb_id_loja.setObjectName("sb_id_loja")
        self.cv_mostrar_loja = QtWidgets.QColumnView(self.buscar_loja)
        self.cv_mostrar_loja.setGeometry(QtCore.QRect(230, 480, 741, 192))
        self.cv_mostrar_loja.setStyleSheet("#cv_mostrar_loja{\n"
"border-radius: 5px;\n"
"}")
        self.cv_mostrar_loja.setObjectName("cv_mostrar_loja")
        self.label_28 = QtWidgets.QLabel(self.buscar_loja)
        self.label_28.setGeometry(QtCore.QRect(231, 431, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.buscar_loja)
        self.label_29.setGeometry(QtCore.QRect(484, 431, 481, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_28.raise_()
        self.label_29.raise_()
        self.frame.raise_()
        self.label_25.raise_()
        self.label_26.raise_()
        self.label_27.raise_()
        self.cb_nome_filial.raise_()
        self.cb_id_loja.raise_()
        self.txt_nome_filial.raise_()
        self.cv_mostrar_loja.raise_()
        self.grafico.addTab(self.buscar_loja, "")
        self.ver_estoque = QtWidgets.QWidget()
        self.ver_estoque.setStyleSheet("")
        self.ver_estoque.setObjectName("ver_estoque")
        self.label_19 = QtWidgets.QLabel(self.ver_estoque)
        self.label_19.setGeometry(QtCore.QRect(280, 110, 111, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.cb_nome_prod_estoque = QtWidgets.QCheckBox(self.ver_estoque)
        self.cb_nome_prod_estoque.setGeometry(QtCore.QRect(251, 79, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(16)
        self.cb_nome_prod_estoque.setFont(font)
        self.cb_nome_prod_estoque.setText("")
        self.cb_nome_prod_estoque.setObjectName("cb_nome_prod_estoque")
        self.label_20 = QtWidgets.QLabel(self.ver_estoque)
        self.label_20.setGeometry(QtCore.QRect(280, 70, 191, 24))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.cb_id_loja_estoque = QtWidgets.QCheckBox(self.ver_estoque)
        self.cb_id_loja_estoque.setGeometry(QtCore.QRect(250, 120, 70, 17))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(16)
        self.cb_id_loja_estoque.setFont(font)
        self.cb_id_loja_estoque.setText("")
        self.cb_id_loja_estoque.setObjectName("cb_id_loja_estoque")
        self.frame_2 = QtWidgets.QFrame(self.ver_estoque)
        self.frame_2.setGeometry(QtCore.QRect(170, 40, 931, 171))
        self.frame_2.setStyleSheet("#frame_2{\n"
"background-color:rgb(194, 194, 194);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.txt_nome_produto_estoque = QtWidgets.QLineEdit(self.frame_2)
        self.txt_nome_produto_estoque.setGeometry(QtCore.QRect(310, 30, 431, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(16)
        self.txt_nome_produto_estoque.setFont(font)
        self.txt_nome_produto_estoque.setStyleSheet("#txt_nome_produto_estoque{\n"
"border-radius: 5px;\n"
"}")
        self.txt_nome_produto_estoque.setObjectName("txt_nome_produto_estoque")
        self.sb_id_loja_estoque = QtWidgets.QSpinBox(self.frame_2)
        self.sb_id_loja_estoque.setGeometry(QtCore.QRect(310, 70, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(16)
        self.sb_id_loja_estoque.setFont(font)
        self.sb_id_loja_estoque.setStyleSheet("#sb_id_loja_estoque{\n"
"border-radius: 5px;\n"
"}")
        self.sb_id_loja_estoque.setMaximum(1000)
        self.sb_id_loja_estoque.setObjectName("sb_id_loja_estoque")
        self.btn_ver_estoque = QtWidgets.QPushButton(self.frame_2)
        self.btn_ver_estoque.setGeometry(QtCore.QRect(740, 110, 161, 32))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        self.btn_ver_estoque.setFont(font)
        self.btn_ver_estoque.setStyleSheet("#btn_ver_estoque{\n"
"background-color:rgb(138, 226, 52);\n"
"border-radius: 5px;\n"
"}")
        self.btn_ver_estoque.setObjectName("btn_ver_estoque")
        self.cv_estoque = QtWidgets.QColumnView(self.ver_estoque)
        self.cv_estoque.setGeometry(QtCore.QRect(170, 300, 931, 321))
        self.cv_estoque.setStyleSheet("#cv_estoque{\n"
"border-radius: 5px;\n"
"}")
        self.cv_estoque.setObjectName("cv_estoque")
        self.label_21 = QtWidgets.QLabel(self.ver_estoque)
        self.label_21.setGeometry(QtCore.QRect(171, 251, 231, 25))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(16)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.ver_estoque)
        self.label_22.setGeometry(QtCore.QRect(320, 250, 231, 25))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(16)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.ver_estoque)
        self.label_23.setGeometry(QtCore.QRect(710, 250, 231, 25))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(16)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.ver_estoque)
        self.label_24.setGeometry(QtCore.QRect(910, 250, 231, 25))
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(16)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.btn_vender_produto = QtWidgets.QPushButton(self.ver_estoque)
        self.btn_vender_produto.setGeometry(QtCore.QRect(960, 660, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_vender_produto.setFont(font)
        self.btn_vender_produto.setObjectName("btn_vender_produto")
        self.label_21.raise_()
        self.label_22.raise_()
        self.label_23.raise_()
        self.label_24.raise_()
        self.frame_2.raise_()
        self.label_19.raise_()
        self.cb_nome_prod_estoque.raise_()
        self.label_20.raise_()
        self.cb_id_loja_estoque.raise_()
        self.cv_estoque.raise_()
        self.btn_vender_produto.raise_()
        self.grafico.addTab(self.ver_estoque, "")
        self.identificador_loja = QtWidgets.QWidget()
        self.identificador_loja.setStyleSheet("")
        self.identificador_loja.setObjectName("identificador_loja")
        self.label_4 = QtWidgets.QLabel(self.identificador_loja)
        self.label_4.setGeometry(QtCore.QRect(280, 90, 261, 41))
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.frame_3 = QtWidgets.QFrame(self.identificador_loja)
        self.frame_3.setGeometry(QtCore.QRect(210, 80, 771, 301))
        self.frame_3.setStyleSheet("#frame_3{\n"
"background-color:rgb(194, 194, 194);\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.txt_senha_conectada = QtWidgets.QTextEdit(self.frame_3)
        self.txt_senha_conectada.setGeometry(QtCore.QRect(70, 160, 261, 41))
        self.txt_senha_conectada.setStyleSheet("#txt_senha_conectada{\n"
"border-radius: 5px;\n"
"}")
        self.txt_senha_conectada.setObjectName("txt_senha_conectada")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(70, 120, 261, 41))
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.sb_func_conectado = QtWidgets.QSpinBox(self.frame_3)
        self.sb_func_conectado.setGeometry(QtCore.QRect(70, 80, 261, 41))
        self.sb_func_conectado.setStyleSheet("#sb_func_conectado{\n"
"border-radius: 5px;\n"
"}")
        self.sb_func_conectado.setMaximum(9999999)
        self.sb_func_conectado.setDisplayIntegerBase(10)
        self.sb_func_conectado.setObjectName("sb_func_conectado")
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setGeometry(QtCore.QRect(70, 40, 261, 41))
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setGeometry(QtCore.QRect(70, 236, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_2.setGeometry(QtCore.QRect(600, 236, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.frame_5 = QtWidgets.QFrame(self.identificador_loja)
        self.frame_5.setGeometry(QtCore.QRect(210, 440, 771, 231))
        self.frame_5.setStyleSheet("#frame_5{\n"
"background-color:rgb(194, 194, 194);\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_7 = QtWidgets.QLabel(self.frame_5)
        self.label_7.setGeometry(QtCore.QRect(60, 20, 301, 41))
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.txt_ip_server = QtWidgets.QTextEdit(self.frame_5)
        self.txt_ip_server.setGeometry(QtCore.QRect(60, 80, 261, 41))
        self.txt_ip_server.setStyleSheet("#txt_senha_conectada{\n"
"border-radius: 5px;\n"
"}")
        self.txt_ip_server.setObjectName("txt_ip_server")
        self.btn_conect_server = QtWidgets.QPushButton(self.frame_5)
        self.btn_conect_server.setGeometry(QtCore.QRect(510, 80, 99, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_conect_server.setFont(font)
        self.btn_conect_server.setObjectName("btn_conect_server")
        self.label_6 = QtWidgets.QLabel(self.identificador_loja)
        self.label_6.setGeometry(QtCore.QRect(210, 400, 261, 41))
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.frame_3.raise_()
        self.label_4.raise_()
        self.frame_5.raise_()
        self.label_6.raise_()
        self.grafico.addTab(self.identificador_loja, "")

        self.retranslateUi(ui_home)
        self.grafico.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ui_home)

    def retranslateUi(self, ui_home):
        _translate = QtCore.QCoreApplication.translate
        ui_home.setWindowTitle(_translate("ui_home", "Dialog"))
        self.label.setText(_translate("ui_home", "MENU DE OPÇÕES"))
        self.btn_cadastrar_loja.setText(_translate("ui_home", "Opções da Loja"))
        self.btn_cadastrar_funcionario.setText(_translate("ui_home", "Opções do Funcionário"))
        self.btn_cadastrar_produto.setText(_translate("ui_home", "Opções de Produto"))
        self.label_2.setText(_translate("ui_home", "Gráfico de Compras"))
        self.btn_atualizar_dia.setText(_translate("ui_home", "Do dia"))
        self.btn_atualizar_mes.setText(_translate("ui_home", "Do mês"))
        self.btn_atualizar.setText(_translate("ui_home", "Atualizar"))
        self.label_3.setText(_translate("ui_home", "Período"))
        self.grafico.setTabText(self.grafico.indexOf(self.pagina_inicial), _translate("ui_home", "Página Inicial"))
        self.label_25.setText(_translate("ui_home", "Buscar Loja"))
        self.label_26.setText(_translate("ui_home", "Nome da Filial"))
        self.label_27.setText(_translate("ui_home", "Identificador"))
        self.btn_buscar_loja.setText(_translate("ui_home", "Buscar"))
        self.label_28.setText(_translate("ui_home", "Id"))
        self.label_29.setText(_translate("ui_home", "Nome"))
        self.grafico.setTabText(self.grafico.indexOf(self.buscar_loja), _translate("ui_home", "Buscar Loja"))
        self.label_19.setText(_translate("ui_home", "Id da Loja"))
        self.label_20.setText(_translate("ui_home", "Nome do Produto"))
        self.btn_ver_estoque.setText(_translate("ui_home", "Ver Estoque"))
        self.label_21.setText(_translate("ui_home", "Id_Produto"))
        self.label_22.setText(_translate("ui_home", "Nome Produto"))
        self.label_23.setText(_translate("ui_home", "Quantidade"))
        self.label_24.setText(_translate("ui_home", "Nome Loja"))
        self.btn_vender_produto.setText(_translate("ui_home", "Vender"))
        self.grafico.setTabText(self.grafico.indexOf(self.ver_estoque), _translate("ui_home", "Ver Estoque"))
        self.label_4.setText(_translate("ui_home", "Funcionario Conetado"))
        self.label_5.setText(_translate("ui_home", "Senha"))
        self.label_8.setText(_translate("ui_home", "CPF"))
        self.pushButton.setText(_translate("ui_home", "LOGIN"))
        self.pushButton_2.setText(_translate("ui_home", "LOGOUT"))
        self.label_7.setText(_translate("ui_home", "Informe o IP do Servidor"))
        self.btn_conect_server.setText(_translate("ui_home", "Conectar"))
        self.label_6.setText(_translate("ui_home", "Conectar ao Servidor"))
        self.grafico.setTabText(self.grafico.indexOf(self.identificador_loja), _translate("ui_home", "Conexão"))

        self.funcionalidades()

    def funcionalidades(self):
        # click de botões
        self.btn_conect_server.clicked.connect(self.conectarServer)
        self.txt_nome_filial.setDisabled(True)
        self.sb_id_loja.setDisabled(True)
        self.txt_nome_produto_estoque.setDisabled(True)
        self.sb_id_loja_estoque.setDisabled(True)
        self.cb_id_loja_estoque.clicked.connect(self.estadoDoCheckBox4)
        self.cb_nome_prod_estoque.clicked.connect(self.estadoDoCheckBox3)
        self.cb_nome_filial.clicked.connect(self.estadoDoCheckBox1)
        self.cb_id_loja.clicked.connect(self.estadoDoCheckBox2)
        self.btn_buscar_loja.clicked.connect(self.buscarDadosDasLojas)
        self.btn_ver_estoque.clicked.connect(self.buscarEstoqueProdutos)


    def buscarEstoqueProdutos(self):
        ip = "127.0.0.1"
        port = 7000
        addr = ((ip, port))
        client_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        client_socket.connect(addr)

        nomeProdutoEstoque = None
        idLojaEstoque = None

        if self.cb_nome_prod_estoque.isChecked() == True:
            nomeProdutoEstoque = self.txt_nome_produto_estoque.text()
        if self.cb_id_loja_estoque.isChecked() == True:
            idLojaEstoque = str(self.sb_id_loja_estoque.value())

        a = "buscarEstoqueHome,"

        client_socket.send((a.encode()))
        mensagem_recebida = client_socket.recv(1024).decode()
        QtWidgets.QMessageBox.about(None, "Home", mensagem_recebida)
        client_socket.close()

    def buscarDadosDasLojas(self):
        ip = "127.0.0.1"
        port = 7000
        addr = ((ip, port))
        client_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        client_socket.connect(addr)

        nomeFilialBuscarLoja = ""
        identificadorLoja = ""

        if self.cb_nome_filial.isChecked() == True:
            nomeFilialBuscarLoja = self.txt_nome_filial.text()
        if self.cb_id_loja.isChecked() == True:
            identificadorLoja = str(self.sb_id_loja.value())

        a = "buscarLojaHome,"

        client_socket.send((a.encode()))
        mensagem_recebida = client_socket.recv(1024).decode()
        QtWidgets.QMessageBox.about(None, "Home", mensagem_recebida)
        client_socket.close()

    def estadoDoCheckBox4(self):
        if self.cb_id_loja_estoque.isChecked() == True:
            self.sb_id_loja_estoque.setDisabled(False)
        else:
            self.sb_id_loja_estoque.setDisabled(True)

    def estadoDoCheckBox3(self):
        if self.cb_nome_prod_estoque.isChecked() == True:
            self.txt_nome_produto_estoque.setDisabled(False)
        else:
            self.txt_nome_produto_estoque.setDisabled(True)

    def estadoDoCheckBox2(self):
        if self.cb_id_loja.isChecked() == True:
            self.sb_id_loja.setDisabled(False)
        else:
            self.sb_id_loja.setDisabled(True)

    def estadoDoCheckBox1(self):
        if self.cb_nome_filial.isChecked() == True:
            self.txt_nome_filial.setDisabled(False)
        else:
            self.txt_nome_filial.setDisabled(True)

    def conectarServer(self):
        ip = self.txt_ip_server.toPlainText()
        port = 7000
        addr = ((ip, port))
        client_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        client_socket.connect(addr)
        print("Entrou!")
        a = "Criar Cliente,"
        client_socket.send((a.encode()))
        mensagem_recebida = client_socket.recv(1024).decode()
        QtWidgets.QMessageBox.about(None, "Conectar", mensagem_recebida)
        self.txt_ip_server.setText("")
        client_socket.close()

        #adicionar loja no produto
        #adicionar o endereço
        #tirar id da loja e colocar nome da filial
        #retirar a tela de buscar produto
        #colocar o botão vender no ver estoque
        #colocar nome cpf para a conexão
        #arquivo para ter o ip do server
        #campo senha no cadastro de funcionário
        #logar funcionário
        #tratamento das entradas


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui_home = QtWidgets.QDialog()
    ui = Ui_ui_home()
    ui.setupUi(ui_home)
    ui_home.showMaximized()
    sys.exit(app.exec_())

